### ISSUE TITLE
Add the ddim sampler

### ISSUE THREAD

**Issue by nan0c0r3** [benrugg/AI-Render#10]
### Describe the feature you'd like to see:

as I know that one of the next features will be the implementation of animations, I suggest adding the sampler ddim. I had better results with coherence between frames using this sampler in Deforum notebook.

**Comment by benrugg** [comment]
Ah, good call. I will do that! Thanks so much for letting me know.

**Comment by benrugg** [comment]
Fixed in 9f354c4ef7c36883e30b6381451d9f85ee650e41
