### ISSUE TITLE
ControlNet won't find models from Automatic 1111 server

### ISSUE THREAD

**Issue by andreaavellino** [benrugg/AI-Render#102]
### Describe the bug

Hello, I successfully installed AI-Render to run locally on my Windows 10 workstation. Now I'm trying to enable ControlNet from AI-Render's interface in Blender, but when I hit "Load Models from Automatic1111" I get this error:

"Couldn't get the list of available ControlNet models from the Automatic111 server. Make sure ControlNet is installed and activated."

I do have ControlNet installed with many models on my Automatic1111, but AI-Render somehow is not able to see it. Am I missing something?

Thank you so much for this incredible tool and for your precious time.

Kindest
Andrea

### To reproduce

- Install Blender 3.5.1
- Install Automatic 1111 web-UI to run locally
- Install ControlNet + models
- Install AI-Render
- Within Ai-Render Blender's UI, under the ControlNet dropdown section, click on "Load Models from Automatic1111

### Error log

ControlNet models returned from Automatic1111 API:
{'detail': 'Not Found'}
AI Render Error: Couldn't get the list of available ControlNet models from the Automatic1111 server. Make sure ControlNet is installed and activated. [Get help](https://github.com/benrugg/AI-Render/wiki/ControlNet)
fake_module: addon missing 'bl_info' gives bad performance!: 'C:\\Users\\intern\\AppData\\Roaming\\Blender Foundation\\Blender\\3.5\\scripts\\addons\\Animated Render Border v3_0.py'

### Environment

- Blender version (upper right corner of splash screen): 3.5.1
- AI Render version (find in Preferences > Add-ons): 0.7.8
- Operating system (Windows/Mac/Linux): Windows 10

### Screenshots/video

<img width="859" alt="Screenshot 2023-05-10 164649" src="https://github.com/benrugg/AI-Render/assets/115216014/2942d80e-225b-4185-bd4b-c3aa01ce7359">

![image](https://github.com/benrugg/AI-Render/assets/115216014/ca0db05f-b258-4e10-9b83-f9c22094f527)

### Additional information

-

**Comment by andreaavellino** [comment]
Hello Ben,

thank you for your answer, I think re-launching the web-UI from cmd did the
work, now it's working.

Kindest,
Andrea





Andrea Avellino
Co-Founder
+39 375 54 67 937
***@***.***

New Format IO GmbH
newformat.io <http://www.newformat.io/>
@newformat.io <https://www.instagram.com/newformat.io/>


This E-Mail and any attached files are confidential and may be legally
privileged.
Disclosure, reproduction, copying, distribution or use of this
communication by other than its addressee is prohibited.
If you received this E-Mail in error, please notify the sender and delete
it immediately.
E-Mail transmission cannot be guaranteed to be secure or error free as
information could be intercepted,
corrupted, lost, destroyed, delayed or incomplete, or contain viruses.
The sender does not accept liability for any losses incurred as a result of
this E-Mail transmission.

**Comment by benrugg** [comment]
Ok, great - thanks for the update!
