### ISSUE TITLE
compositor node not created

### ISSUE THREAD

**Issue by Barracuda77** [benrugg/AI-Render#107]
### Describe the bug

after rendering the view switched to the AI render tab but the compositor view is empty there are no nodes there.

### To reproduce

every image I render has no compositor nodes 

### Error log

[log.txt](https://github.com/benrugg/AI-Render/files/11520406/log.txt)

### Environment

- Blender version (upper right corner of splash screen): 3.5.1
- AI Render version (find in Preferences > Add-ons): 0.7.8
- Operating system (Windows/Mac/Linux): Ubuntu 22.04.2 LTS

**Comment by benrugg** [comment]
Yes, I actually remove the nodes in the most recent version of AI Render, because I needed to find a new workflow that would support upscaling. So now it's expected behavior to not have the nodes.
