### ISSUE TITLE
Changing in COMMANDLINE add api

### ISSUE THREAD

**Issue by mike-iv** [benrugg/AI-Render#108]
### Describe the bug

when I change #export COMMANDLINE_ARGS="" to export COMMANDLINE_ARGS="--api" (In vim (the text editor), Web Ui not loads, gives error

### To reproduce

When I add to webui-user.sh export COMMANDLINE_ARGS="--api"
Terminal gives an error 

RuntimeError: Error running command.
Command: "/Users/mikeiv/stable-diffusion-webui/venv/bin/python3.10" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

If I add export COMMANDLINE_ARGS="--skip-torch-cuda-test”

(mpsFileLoc): /AppleInternal/Library/BuildRoots/c2cb9645-dafc-11ed-aa26-6ec1e3b3f7b3/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:228:0: error: 'mps.add' op requires the same element type for all operands and results
(mpsFileLoc): /AppleInternal/Library/BuildRoots/c2cb9645-dafc-11ed-aa26-6ec1e3b3f7b3/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShadersGraph/mpsgraph/MetalPerformanceShadersGraph/Core/Files/MPSGraphUtilities.mm:228:0: note: see current operation: %7 = "mps.add"(%6, %arg2) : (tensor<2x1280xf32>, tensor<*xf16>) -> tensor<*xf32>
zsh: segmentation fault  ./webui.sh
(base) mikeiv@mikhailacStudio stable-diffusion-webui % /opt/homebrew/Cellar/python@3.10/3.10.10_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

### Error log

Last login: Tue May 23 17:34:21 on ttys000
(base) mikeiv@mikhailacStudio ~ % cd /Applications/Blender.app/Contents/MacOS && ./Blender
Read prefs: /Users/mikeiv/Library/Application Support/Blender/3.5/config/userpref.blend
Device with name Apple M1 Max supports metal minimum requirements
METAL API - DETECTED GPU: Apple M1 Max
Read blend: /Users/mikeiv/текущие проекты/Gatchina mapping/gatchina mapping.blend
AI Render Error: The local Stable Diffusion server couldn't be found. It's either not running, or it's running at a different location than what you specified in the add-on preferences. [Get help](https://github.com/benrugg/AI-Render/wiki/Local-Installation)
AI Render Error: The local Stable Diffusion server couldn't be found. It's either not running, or it's running at a different location than what you specified in the add-on preferences. [Get help](https://github.com/benrugg/AI-Render/wiki/Local-Installation)

### Environment

- Blender version (upper right corner of splash screen): 3.5.1
- AI Render version (find in Preferences > Add-ons): 0.7.8
- Operating system (Windows/Mac/Linux): Mac OS 13.4

**Comment by benrugg** [comment]
This is actually an issue with Automatic1111, so you might have to get help from their community to get it all running. I would suggest trying this line, and if it still doesn't work, see if the Automatic1111 people can help:

`export COMMANDLINE_ARGS="--api --no-half --skip-torch-cuda-test"`

**Comment by benrugg** [comment]
I'm going to close this, but feel free to let me know if you get it working or still can't!

**Comment by mike-iv** [comment]
Thank you for line suggestion, now blender and Automatic1111 work

**Comment by benrugg** [comment]
Great. Yeah, it's such a beast to set up, but it should run well now you've got it!
