### ISSUE TITLE
Out of memory issue

### ISSUE THREAD

**Issue by Made-0f-Ice** [benrugg/AI-Render#109]
### Describe the bug

I have out-of-memory bug in the addon, although web-ui is working well. GPU-memory (used in Blender) is about 2Gb while 10Gb are free. And it runs out of memory while rendering with AI-Render addon

### To reproduce

I use local installation of latest SD-Automatic1111 (with RTX 3070Ti 12Gb card), which is working fine with web-ui. I set EEVEE engine to use CPU for render and keep GPU fresh. But when I connect to the local Stable-Diffusion server from AI-Render Addon, it immediately runs out of memory

### Error log

LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Applying optimization: sdp-no-mem
Textual inversion embeddings loaded(0): 
Model loaded in 1.8s (load weights from disk: 0.5s, create model: 0.3s, apply weights to model: 0.5s, apply half(): 0.3s, move model to device: 0.2s).
API error: POST: http://127.0.0.1:7860/sdapi/v1/img2img {'error': 'OutOfMemoryError', 'detail': '', 'body': '', 'errors': 'CUDA out of memory. Tried to allocate 2.75 GiB (GPU 0; 11.73 GiB total capacity; 8.03 GiB already allocated; 1.46 GiB free; 8.91 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF'}

### Environment

- Blender version (upper right corner of splash screen): 3.6 beta (locally compiled)
- AI Render version (find in Preferences > Add-ons): 0.7.8 (from https://github.com/benrugg/AI-Render/releases/download/v0.7.8/AI-Render-v0-7-8.zip)
- Operating system (Windows/Mac/Linux): Debian Linux
- Python version: 3.11.3

### Screenshots/video

P.S. Screenshot from SD web-ui processing of the same render attached

![Screenshot_20230527_013620](https://github.com/benrugg/AI-Render/assets/134744068/4b76e96c-cd85-400b-8b3f-0ed24c477b84)

**Comment by benrugg** [comment]
Huh, that sucks to hear. I'm sorry this issue is happening for you. I would guess that it might be due to a recent change in Automatic1111, because I haven't seen this happen before (and they're updating it constantly!). 

Unfortunately, I can't help with this, but maybe the Automatic1111 community can. Try posting it there, or see if anyone else is having memory issues when using the API. (That's the wording to use. "api memory issues"). 

Let me know what you find out.
