### ISSUE TITLE
Render image not working

### ISSUE THREAD

**Issue by elliskt** [benrugg/AI-Render#11]
### Describe the bug

Hi, I tried to use AI Render but after I clicked Render Image, it was showing the original image from Blender. Blueprint showed that it was connected to AI Render

### To reproduce

1. installed AI Render in Blender
2. size, prompts, style selected
3. Render Image but AI Render not working (showing the same original image)

### Environment

- AI Render version: 0.2.6
- Blender version: latest
- Operating system: (Windows)

**Comment by benrugg** [comment]
@elliskt, please try the latest release and let me know if you still have an issue. Definitely send an error log if you can. I will close this issue soon if I don't hear back.
