### ISSUE TITLE
After updating Nvidia driver, AI Render no longer producing results

### ISSUE THREAD

**Issue by designborg** [benrugg/AI-Render#113]
### Describe the bug

I was getting results from AI Render, then I updated my Titan RTX device to the latest driver. Now the render result ignores the AI Render pass (process) and just returns the scene as is - without AI

### To reproduce

No specific steps to report

### Error log

No error log to report

### Environment

- Blender version: 3.6 Beta
- AI Render version: 0.7.9
- Operating system: Windows 10

**Comment by benrugg** [comment]
Sorry to hear this! This means there is an issue in automatic1111, which I unfortunately can't help with. Try posting in their GitHub community, and hopefully they'll be able to help!

**Comment by designborg** [comment]
Thank you for sending me in the right direction. I was able to learn that I needed to install an early version of my GPU driver. That fixed the problem.

**Comment by benrugg** [comment]
Great, glad to hear it
