### ISSUE TITLE
ReferenceError: StructRNA of type Scene has been removed

### ISSUE THREAD

**Issue by Razlad** [benrugg/AI-Render#12]
### Describe the bug

I installed the Blender addon and added the api key from the website then tried to render but there were no changes in the render whatsoever

### To reproduce

followed the Tutorial

### Error log

no error log alerts

### Environment

- Blender version (upper right corner of splash screen): 3,30
- AI Render version (find in Preferences > Add-ons):  0,2,8
- Operating system (Windows/Mac/Linux): Windows

**Comment by benrugg** [comment]
I'll do my best to help. The only way I'll be able to track it down is with an error log. In Blender, go to Window > Toggle System Console and then copy and paste what you see there.

**Comment by Aekschen** [comment]
I have the same behavior as @Razlad 

I get this in the system console:

```
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\AI-Render\task_queue.py", line 12, in execute_queued_functions
    function()
  File "C:\Users\xxx\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\AI-Render\operators.py", line 274, in send_to_api
    props = scene.air_props
ReferenceError: StructRNA of type Scene has been removed
```

**Comment by benrugg** [comment]
@Aekschen this is interesting. Thanks for posting the log. I will see if I can track this down!

**Comment by benrugg** [comment]
Does anyone still see this error in the more recent versions of AI Render?

**Comment by kiuet** [comment]
yes, i don't show AI image and it shows error code.
![Screenshot 2022-12-02 133942](https://user-images.githubusercontent.com/119653801/205232406-7fe825b5-1d57-4d60-b75a-ba8d7b3bed21.png)

**Comment by kiuet** [comment]
> Does anyone still see this error in the more recent versions of AI Render?
I don't show AI image and it shows error log.
when it doesn't show the error character it still doesn't show the image Ai

>

**Comment by kiuet** [comment]
![Screenshot 2022-12-02 142259](https://user-images.githubusercontent.com/119653801/205237987-352e5fbb-7022-4b93-bc18-077fce547ad9.png)

**Comment by eyesoflamia** [comment]
Hi all, yeah came here to look for my error too, and it seems I'm getting something very similar too. Blender version 3.3.1 and 2.5 something (I had that installed earlier, so tried on that first, then updated). The AI Render engine version 0.5.3. Getting same kiuet. 
![error](https://user-images.githubusercontent.com/119674146/205295991-7b4f7b07-33b1-488b-bac0-0887f8dea29f.JPG)

**Comment by eyesoflamia** [comment]
Oh I just tried the latest version on here on GitHub 0.6.4 and that works well. Thank you!

**Comment by benrugg** [comment]
@eyesoflamia Thank you for confirming that the new version fixed this. @kiuet this will fix your issue as well. (Just update in the AI Render add-on preferences).

@Razlad and @Aekschen, I'm curious if you see the StructRNA error with the newest version of AI Render.

**Comment by kiuet** [comment]
Oh, version 0.6.6 works great
