### ISSUE TITLE
AttributeError: 'str' object has no attribute 'scene'

### ISSUE THREAD

**Issue by googolhkl** [benrugg/AI-Render#123]
### Describe the bug

hello. I used the Ai Render (V0-9-0) version in blender 3.6 and there is no change over time as shown in the following image. 

### To reproduce

Ai Render - Change Image Size - Typed in prompt - Render Image(F12)

### Error log

Traceback (most recent call last):
  File "C:\Users\googo\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\AI-Render\handlers.py", line 21, in load_post_handler
    if context.scene.air_props.is_enabled:
AttributeError: 'str' object has no attribute 'scene'

### Environment

- Blender version (upper right corner of splash screen): 3.6.0
- AI Render version (find in Preferences > Add-ons): 0.9.0
- Operating system (Windows/Mac/Linux): Windows11

### Screenshots/video

![화면 캡처 2023-07-13 115557](https://github.com/benrugg/AI-Render/assets/8174471/c876d4a8-c652-4de1-82b2-aad8f409088d)

After a while, it didn't change, so I checked the console and saw the following error message.

![화면 캡처 2023-07-13 115825](https://github.com/benrugg/AI-Render/assets/8174471/4fa31576-4fd2-475c-85eb-ce389f1c4664)

Is this a bug?

**Comment by benrugg** [comment]
Thank you for posting this! I've replicated this on my end just now with Blender 3.6. I should be able to push a fix today. Otherwise, Blender 3.0-3.5 work right now.

**Comment by benrugg** [comment]
Fixed in 43a9b0048e941f1170f67853c3c8c8508a7f7add. Released here: https://github.com/benrugg/AI-Render/releases/tag/v0.9.1

You should be able to update through AI Render's add-on preferences. And I will update Blender Market and Gumroad in the next few minutes!
