### ISSUE TITLE
Local installation: Ai renders but won't show in Blender

### ISSUE THREAD

**Issue by migero** [benrugg/AI-Render#13]
### Describe the bug

Blender will not show the resault image
Blender's system console is not helping much too

### To reproduce

Rendering scene with Local Backend (Automatic1111 before Oct 21)
will resault in image beeing processed as expected
(shows progress in webUI console and can find the image in webUI output folder)

### Error log

AI Render Error:  Couldn't load the image from Stable Diffusion

### Environment

- Blender version 3.3.0
- AI Render version 0.3.3
- Operating system Windows 10
- WebUI running on Anaconda Environment

**Comment by benrugg** [comment]
If it's not working with Automatic1111, it's probably because it's not the right version of it. I've added more to the instructions, and now included a section about how to get it to the right commit version. Try this: https://github.com/benrugg/AI-Render/wiki/Local-Installation

**Comment by benrugg** [comment]
I just made a new release that should work much more reliably with Automatic1111 going forward. You'll need to follow slightly updated instructions (the key difference being that you will now enable `API` mode): https://github.com/benrugg/AI-Render/wiki/Local-Installation

**Comment by benrugg** [comment]
Fixed in 433637e39bfd10fb39ed1489e1bf4266d75c2067
