### ISSUE TITLE
Feature Request: Add the ability to override the filename

### ISSUE THREAD

**Issue by LeonardMeagher2** [benrugg/AI-Render#132]
### Describe the feature you'd like to see:

There is currently an issue asking to add more info to the filename #44 
My request is to actually allow overriding the with custom formatting.

Instead of formatting a predefined string here
https://github.com/benrugg/AI-Render/blob/75acec4a5d4ac18624df6b915328225afbcc24f2/operators.py#L367
using something like
```python
def sd_generate(scene, prompts=None, use_last_sd_image=False, custom_filename="ai-render-{timestamp}-{suffix}"):
.....
  before_output_filename_prefix = cutom_filename.format(timestamp = timestamp, seed = seed, suffix = "-1-before")
....
```

Giving the option to add more info, or in my case where I want the filename to be the same every render. Since I don't want a bunch of images for each render, just whatever the last one was.

**Comment by LeonardMeagher2** [comment]
I realize the issue I linked it's mentioned that this might be on the roadmap.
I might open a PR and see if what I have in mind is acceptable.

**Comment by benrugg** [comment]
Yeah, if you want to implement something and submit a PR, I'm happy to review it! I'm going to reopen this for now.

**Comment by benrugg** [comment]
This feature is now available, thanks to @LeonardMeagher2. Update AI Render through the add-on preferences and you can specify a template for the filename.
