### ISSUE TITLE
Connecting to Automatic1111 local remotely

### ISSUE THREAD

**Issue by claychinasky** [benrugg/AI-Render#135]
### Describe the bug

I have a local remote network setup that I route remote localhosts via nginx to local (via vpn), which means I can use remote localhosts `https://local.myserver.com/port/` as locally

The problem is that the addon doesn't seem to connect it where I can access the api with browser `https://local.myserver.com/port/docs` for example.

Not sure what is the problem now but I suspect maybe its `https` related or websockets if api workflow uses it?

### To reproduce

---

### Error log

no error has shown except blender says, couldn't find SD backend.

### Environment

- Blender version (upper right corner of splash screen): 3.6.4
- AI Render version (find in Preferences > Add-ons): 0.10.0
- Operating system (Windows/Mac/Linux): win11

**Comment by benrugg** [comment]
Thanks for posting this. I imagine this should be fixable without too much trouble 🤞

Just to clarify, I'm assuming you're setting "Local Web Server URL" to the url that you can see in your browser, and it's silently failing?

Could you get the the log from the Blender Console? (`Window > Toggle System Console`)

<img width="477" alt="Screenshot 2023-10-26 at 9 12 05 AM" src="https://github.com/benrugg/AI-Render/assets/1221274/95da69a5-1a33-431e-8070-ab80f7003249">

**Comment by claychinasky** [comment]
after running this example code :
```python
import json
import requests
import io
import base64
from PIL import Image

url = "http://127.0.0.1:7860"

payload = {
    "prompt": "puppy dog",
    "steps": 5
}

response = requests.post(url=f'{url}/sdapi/v1/txt2img', json=payload)

r = response.json()

image = Image.open(io.BytesIO(base64.b64decode(r['images'][0])))
image.save('output.png')
```
I get this error, I guess this might be the issue?
```
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Hostname mismatch, certificate is not valid for 'local.myserver.eu'. (_ssl.c:1007)
```

**Comment by benrugg** [comment]
That error would definitely lend validity to your intuition that it might be an issue with HTTPS/SSL. If that's the case, I think you'll need to figure out how to get the cert issue working. I'm not sure how to help, but I think there are command line tools you can run if you can find them.

**Comment by benrugg** [comment]
Yeah, that's a good call. And separately, I assume this is a dumb question, but you did change the Automatic1111 config so it's running in API mode, correct?

**Comment by claychinasky** [comment]
yes, I did, also fiddled with CORS settings and TSL settings but they did not solve anything.

**Comment by LeonardMeagher2** [comment]
Could try setting `verify=False` in the requests, maybe turn that into a checkbox in that config window?

**Comment by benrugg** [comment]
> Could try setting `verify=False` in the requests, maybe turn that into a checkbox in that config window?

Good call. @claychinasky, did you end up fixing it by using http instead of https?

**Comment by claychinasky** [comment]
Well I regenerated my SSL certificate now it's connecting and generating with API via example code that I posted previously. 🎉 

But AI-Render addon I think it connects? and it gives this error:
`AI Render Error: Couldn't create temp file for image`

**Comment by benrugg** [comment]
Ok, glad that the ssl issue was sorted out! The temp file is a rare issue that I've heard of a few times from others. AI Render temporarily puts the returned image from Automatic1111 in the system's temp file storage `/tmp/...` or `C:\temp` or whatever the OS allows internally. I think the error you're seeing is a disk permissions error, but I'm not sure how to fix it. If you happen to know that you've locked down your system in some way that you can change back, I'd love to know how to handle it!

**Comment by claychinasky** [comment]
hmm, I tried running with as Admin but it gave the same error.
I will try to inspect the code but is it possible that it tries to create temp file from server? dunno yet.

**Comment by claychinasky** [comment]
Just a note that,
if I check the box for `Apply a Preset Style` then error is `AI Render Error: Couldn't create temp file for image`

if I uncheck it error is `AI Render Error: An error occurred in the Automatic1111 Stable Diffusion server. Check the server logs for more info.
Error: An error occurred in the Automatic1111 Stable Diffusion server. Check the server logs for more info.` 

and there is no error in A1111 server side, dunno about api logs will check that too.

**Comment by benrugg** [comment]
Hmm, that's very strange that it gives a different error with/without the preset style checked. My guess is that there's still some issue getting the image from Automatic1111 (even if there's no error on its side). 

Could you try either running Automatic1111 from its standard url `http://127.0.0.1:7860` or using DreamStudio? If either of those work, it means that the error is somehow still getting spurred by connecting to Automatic1111 at your proxied url. And if those don't work, then hopefully we can track down where the error is happening.

**Comment by claychinasky** [comment]
I will try that also I installed this [https://github.com/thndrbrrr/gimp-stable-boy](url) and it worked right away.

**Comment by benrugg** [comment]
@claychinasky, just in case you didn't get a notification on this new issue, could you see #136

**Comment by benrugg** [comment]
@claychinasky I fixed one of the issues you saw yesterday. Update AI Render through the add-on preferences to get the latest version (0.10.1). Let me know if you're still seeing issues with the custom url and/or the standard url. 

I appreciate your patience through all of this! Normally the add-on works great!

**Comment by claychinasky** [comment]
@benrugg yes, issue seems to have solved! Thanks for fixing it.

**Comment by benrugg** [comment]
Well... I'm glad it's working. But, ugh, I'm sorry there's another bug! Yeah, if you don't mind, open a new issue for that, and I will tackle it as soon as I can. (Hopefully Monday).
