### ISSUE TITLE
Error: Couldn't create temp file

### ISSUE THREAD

**Issue by benrugg** [benrugg/AI-Render#136]
It seems like the latest version of AI Render (0.10.0) may have introduced an occasional bug when trying to create a temp file to save the AI image. 

@afecelis and @claychinasky, I think you both saw this bug. I'm wondering if it's an issue with special characters in the filename, or having too many characters in the filename (now that the prompt is saved in the filename by default). 

@claychinasky, this would explain why you saw this error when you had the preset activated, but not when it wasn't activated. 

Could either of you post what your prompt and preset were?

**Comment by afecelis** [comment]
Prompt:
realistic modern [livingroom] very detailed, wide camera angle 20mm, hyper sharp focus, super resolution, stunning intricate detail, photorealistic, dramatic lighting, octane render, [white]  furniture, ultra realistic, 8k

Preset Style:
Product Shot

Thank you! Please let us know if you're able to fix it.
Regards,

Alvaro

**Comment by benrugg** [comment]
@afecelis, great, thank you. I got it fixed and I'll push a release in a minute.

**Comment by afecelis** [comment]
yesssssssssssssssssssssssssssssssssssss!!!!!!!   Thank you Ben!

**Comment by benrugg** [comment]
Fixed in 1766f6722928423af596dae8016e4415fba1043b

Update AI Render in the add-on preferences and it should work now. Definitely let me know here if you still see an error!

**Comment by afecelis** [comment]
@benrugg I will, looking forward to further development, hope to be able to contribute somehow soon.

**Comment by afecelis** [comment]
Starting to get the hang of it!
Very simple cen in blender:
https://ibb.co/hdw9kJj
https://ibb.co/CwtcHqM
https://ibb.co/N38QTgx
https://ibb.co/7t3q4wv
https://ibb.co/yp2XYvd

**Comment by benrugg** [comment]
@afecelis Really glad it's all working for you. It sounds like you figured it out already, but yes, you can set whatever command line flags you want. I don't think it works with Lora's, but let me know if you're getting it to work with a Lora model.

**Comment by afecelis** [comment]
No Loras yet. Some animation tests
https://www.youtube.com/shorts/e6XhZPKfcvI?feature=share
https://www.youtube.com/shorts/L0_l0VkwFbU?feature=share
