### ISSUE TITLE
Texturing extension

### ISSUE THREAD

**Issue by solosails** [benrugg/AI-Render#139]
### Describe the feature you'd like to see:

Hi there, This addon is amazing, thank you for all the work to date and releasing it to the community!

So, I have just installed it again having tried it a couple of years ago, and its reminded me just how much potential it has to expand. I was using the setup to take a model with a photographic texture, export that texture to AI to create a new style, then re project back onto the model.

This is all fine , but a nice option might be to have that facility built into the plugin, so, basically, you don't just get an AI image back you also have the option to re-project the texture back onto the model. 

Also, the ability to export the blender depth map to a control net would be incredibly handy!

I realise its easy for me to request this as a non coder and can see it wouldn't be trivial, but it would be great to see this addon develop some more!

Just a though - thanks again!

**Comment by solosails** [comment]
Hi, Thanks for getting back so quickly! Sorry, I didn't see the other post - and I found that Dream Texture addon almost as soon as I'd posted this - seems like it is a direction it should go in then. Sorry you haven't got time to keep this awesome plugin developing, I only wish I had the coding skills to help!

**Comment by benrugg** [comment]
Ok, that's good to know. I hope someone else can contribute to this, as well!
