### ISSUE TITLE
Does not render locally

### ISSUE THREAD

**Issue by CRYOMEN** [benrugg/AI-Render#141]
### Describe the bug

Hi,

It does not render on local SD installation. When I click "Render / Render Image" it renders using default EEVEE. No errors in both consoles.

Just in case "Render AI" tab also does not showup like in videos.

### To reproduce

Just install as described in Documentation, make your prompt and run "Render / Render Image".

### Error log

No logs

### Environment

- Blender version: 4.0
- AI Render version: 1.0.1
- Operating system: Windows

**Comment by benrugg** [comment]
Hey @CRYOMEN, sorry to hear that it's not working for you. Thanks for mentioning that there's nothing in either error log. That's definitely odd. Assuming that you still have the "run automatically" checkbox checked (under the "Operation" tab in AI Render), it should render or at the very least show an error. 

Can you try switching to DreamStudio in AI Render's preferences and see if it gives you an error. (You don't even need to sign up for it or get a key. Just try rendering without it and you should at least get a message).

**Comment by CRYOMEN** [comment]
> Hey @CRYOMEN, sorry to hear that it's not working for you. Thanks for mentioning that there's nothing in either error log. That's definitely odd. Assuming that you still have the "run automatically" checkbox checked (under the "Operation" tab in AI Render), it should render or at the very least show an error.
> 
> Can you try switching to DreamStudio in AI Render's preferences and see if it gives you an error. (You don't even need to sign up for it or get a key. Just try rendering without it and you should at least get a message).

Oh! "run automatically on render" was not checked. Now its works as expected. Thank you a lot!

**Comment by benrugg** [comment]
Oh great - I'm glad it was an was an easy fix!
