### ISSUE TITLE
All Images are censored

### ISSUE THREAD

**Issue by Lesekater** [benrugg/AI-Render#143]
### Describe the bug

I installed the newest version of the plugin but all images i genereate come back as "CENSORED Potentially CSAM content detected and had to be blocked."

[system-info.txt](https://github.com/benrugg/AI-Render/files/15139617/system-info.txt)

### To reproduce

install plugin, select stable horde and insert api key, insert any prompt and try to render

### Error log

WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1360 pyrna_enum_to_py: current value '120' matches no enum in 'AIRProperties', '', 'sampler'
Read blend: "/tmp/quit.blend"
WARN (bpy.rna): source/blender/python/intern/bpy_rna.cc:1360 pyrna_enum_to_py: current value '120' matches no enum in 'AIRProperties', '', 'sampler'
Sending request to Stable Horde API: https://stablehorde.net/api/v2/generate/async
Checking status of request at Stable Horde API: https://stablehorde.net/api/v2/generate/check/da38ad65-a1f6-488c-9a73-cc1237d98b83
Waiting for 5.217092847000458s. Response: {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 30, 'queue_position': 0, 'kudos': 1.0, 'is_possible': True}
Checking status of request at Stable Horde API: https://stablehorde.net/api/v2/generate/check/da38ad65-a1f6-488c-9a73-cc1237d98b83
Waiting for 6.791966630000388s. Response: {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 29, 'queue_position': 0, 'kudos': 1.0, 'is_possible': True}
Checking status of request at Stable Horde API: https://stablehorde.net/api/v2/generate/check/da38ad65-a1f6-488c-9a73-cc1237d98b83
Waiting for 8.309659427992301s. Response: {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 27, 'queue_position': 0, 'kudos': 1.0, 'is_possible': True}
Checking status of request at Stable Horde API: https://stablehorde.net/api/v2/generate/check/da38ad65-a1f6-488c-9a73-cc1237d98b83
Waiting for 9.551381412995397s. Response: {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 26, 'queue_position': 0, 'kudos': 1.0, 'is_possible': True}
Checking status of request at Stable Horde API: https://stablehorde.net/api/v2/generate/check/da38ad65-a1f6-488c-9a73-cc1237d98b83
Waiting for 10.86774796199461s. Response: {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 25, 'queue_position': 0, 'kudos': 1.0, 'is_possible': True}
Checking status of request at Stable Horde API: https://stablehorde.net/api/v2/generate/check/da38ad65-a1f6-488c-9a73-cc1237d98b83
Waiting for 12.58684327499941s. Response: {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 23, 'queue_position': 0, 'kudos': 1.0, 'is_possible': True}
Checking status of request at Stable Horde API: https://stablehorde.net/api/v2/generate/check/da38ad65-a1f6-488c-9a73-cc1237d98b83
Waiting for 13.809171808999963s. Response: {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 22, 'queue_position': 0, 'kudos': 1.0, 'is_possible': True}
Checking status of request at Stable Horde API: https://stablehorde.net/api/v2/generate/check/da38ad65-a1f6-488c-9a73-cc1237d98b83
Waiting for 15.360305102993152s. Response: {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 20, 'queue_position': 0, 'kudos': 1.0, 'is_possible': True}
Checking status of request at Stable Horde API: https://stablehorde.net/api/v2/generate/check/da38ad65-a1f6-488c-9a73-cc1237d98b83
Waiting for 16.590320029994473s. Response: {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 19, 'queue_position': 0, 'kudos': 1.0, 'is_possible': True}
Checking status of request at Stable Horde API: https://stablehorde.net/api/v2/generate/check/da38ad65-a1f6-488c-9a73-cc1237d98b83
Waiting for 17.915043945002253s. Response: {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 18, 'queue_position': 0, 'kudos': 1.0, 'is_possible': True}
Checking status of request at Stable Horde API: https://stablehorde.net/api/v2/generate/check/da38ad65-a1f6-488c-9a73-cc1237d98b83
Waiting for 19.466331589996116s. Response: {'finished': 0, 'processing': 1, 'restarted': 0, 'waiting': 0, 'done': False, 'faulted': False, 'wait_time': 16, 'queue_position': 0, 'kudos': 1.0, 'is_possible': True}
Checking status of request at Stable Horde API: https://stablehorde.net/api/v2/generate/check/da38ad65-a1f6-488c-9a73-cc1237d98b83
Waiting for 21.034678916999837s. Response: {'finished': 1, 'processing': 0, 'restarted': 0, 'waiting': 0, 'done': True, 'faulted': False, 'wait_time': 0, 'queue_position': 0, 'kudos': 2.0, 'is_possible': True}
The horde took 21.03480679700442s to imagine this frame.
Retrieving image from Stable Horde API: https://stablehorde.net/api/v2/generate/status/da38ad65-a1f6-488c-9a73-cc1237d98b83
Worker: Apytele, kudos: 2.0
Retrieving image file from R2: https://a223539ccf6caa2d76459c9727d276e6.r2.cloudflarestorage.com/stable-horde/08a75349-c215-4a7d-993a-d316ea8841db.webp?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=246782cc9101762ba914350d8058cd83%2F20240427%2Fauto%2Fs3%2Faws4_request&X-Amz-Date=20240427T194713Z&X-Amz-Expires=1800&X-Amz-SignedHeaders=host&X-Amz-Signature=97383607032712023ac3076e38095e839d7bffedaf95d2775c8e699d7573d446

### Environment

- Blender version (upper right corner of splash screen): 4.1
- AI Render version (find in Preferences > Add-ons): 1.0.1
- Operating system (Windows/Mac/Linux): Linux

**Comment by benrugg** [comment]
Hmm, that's interesting. I think unfortunately Stable Horde is probably not a great option anymore. I don't have enough time to track down this error, but it looks like it's coming from Stable Horde itself, rather than from AI Render. I would suggest using DreamStudio instead!
