### ISSUE TITLE
STL

### ISSUE THREAD

**Issue by thom1948** [benrugg/AI-Render#148]
### Describe the feature you'd like to see:

Would it be possible to create a model suitable to export to an STL file?

**Comment by benrugg** [comment]
That's a good question - I think a lot of people are working on this, and I think there are some early options like these:

- https://www.meshy.ai/
- https://3dfy.ai/services#3DFYPrompt

These don't work with my add-on, but they're something you could test out, at least. 

This is also a good Blender add-on that might do what you're looking for: https://blendermarket.com/products/dream-textures

**Comment by thom1948** [comment]
Ok, thanks
