### ISSUE TITLE
API needs update - esrgan-v1-x2plus error

### ISSUE THREAD

**Issue by Wesselius7** [benrugg/AI-Render#155]
### Describe the bug

The AI Render does not produce a result.

### To reproduce

Hello,
I have installed AI Render in Blender that uttilzes Dreamsupport. I have also added my API key in the control window. When I render I get a Server error that prompts "An error occurred in the Stability API. Full server response: The specified engine (ID esrgan-v1-x2plus) was not found."

I reached out to Stability.ai, and the answered:

It appears that AI Render, a 3rd party application was utilizing our Upscaler model (esrgan-v1-x2plus) via our API. We deprecated this model as we offer an improved suite of upscale models, also available via our API.  We suggest reaching out to the AI Render team to inform them of this change so they can update their add-on as needed. 
Can you help me out?

### Error log

An error occurred in the Stability API. Full server response: The specified engine (ID esrgan-v1-x2plus) was not found

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux):

**Comment by benrugg** [comment]
@Wesselius7 oh, thank you for posting this. I will fix it ASAP!

**Comment by wassabier** [comment]
I faced same Error, is it solved ? or is there any way to solve? 
![Screenshot 2024-10-21 at 3 15 19 pm](https://github.com/user-attachments/assets/81d86410-caad-429a-8820-b0f8c1227208)

**Comment by benrugg** [comment]
@wassabier I did not have a chance to fix this over the weekend, but I will get to it very soon! For now, you can uncheck "upscale automatically" in the AI Render options.

**Comment by benrugg** [comment]
@wassabier This is now fixed. You can update AI Render in Blender's add-on preferences and it should all work well!
