### ISSUE TITLE
Can't get automatic 1111 API to run on Mac M3

### ISSUE THREAD

**Issue by AukeDC** [benrugg/AI-Render#157]
### Describe the bug

I can run Automatic 1111 just fine but is soon as I enter this code:

"export COMMANDLINE_ARGS="--api"

into webui-user.sh and try to run automatic 1111 I get this error:

"RuntimeError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check"

Without this code I get the following error in Blender 3D:

"It looks like the Automatic1111 server is running, but it's not in API mode"

If I add 

"--skip-torch-cuda-test"

together with the API code it seems to disable the API code.

I can't seem to add the right code to skip the cuda test AND use the API. It seems to do one or the other. What am I doing wrong?

Thanks a lot!

### To reproduce

I followed the steps to install automatic 1111 and AI render and did the steps I listed above.

### Error log

AI Render Error: The local Stable Diffusion server couldn't be found. It's either not running, or it's running at a different location than what you specified in the add-on preferences. [Get help](https://github.com/benrugg/AI-Render/wiki/Local-Installation)

### Environment

- Blender Version 4.2.3 (4.2.3 2024-10-15)
- AI Render version 1.0.1
- MacOS Sonoma 14.5
- Macbook Pro M3 Max

**Comment by benrugg** [comment]
Then make sure you run `./webui.sh` (not `webui-user.sh`). 

I'm going to close this issue, but let me know if you still can't get it working!

**Comment by AukeDC** [comment]
Thanks so mush for your fast response!
I've been shewing on this for days.

It works but now I get the following error in both Blender alswall as in automatic 1111 as a standalone:

TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.

**Comment by benrugg** [comment]
Oh, right, even though Mac's have a super powerful processor, it's not actually set up to run the AI stuff in python fully. Try these - I think one should work:

```
export COMMANDLINE_ARGS="--api --skip-torch-cuda-test --no-half"
```

```
export COMMANDLINE_ARGS="--api --skip-torch-cuda-test --no-half --use-cpu"
```

```
export COMMANDLINE_ARGS="--api --skip-torch-cuda-test --no-half --use-cpu all"
```

**Comment by benrugg** [comment]
(I use a Mac and tested predominantly on a Mac M1 and M2 during development, so it will definitely work once the config is right! I hate that Automatic1111 made everything so difficult to setup)

**Comment by AukeDC** [comment]
After switching checkpoints it seems to work with your original code, even if a switch back to the first checkpoint that gave the error. I'll try the other codes if the error comes back or as a test for speed improvements. I'll report back when I find the time.

Thank a lot!

**Comment by benrugg** [comment]
Ah, nice. Great. I hope you enjoy it!
