### ISSUE TITLE
Possibility to add multiple model, not only Stable Diffusion v1

### ISSUE THREAD

**Issue by gioxyer** [benrugg/AI-Render#159]
### Describe the feature you'd like to see:

So I noticed that the addon use only stable diffusion v1, add the possibility to use sdxl and flux, thanks

**Comment by benrugg** [comment]
Actually, I added SDXL support on the day it came out (about 18 months ago, I think!) https://github.com/benrugg/AI-Render/releases/tag/v0.7.6

I've been trying to keep AI Render updated with everything available through DreamStudio (StableDiffusion's API), but you can also use any model you want if you run it locally with something like Automatic1111.
