### ISSUE TITLE
Render Animation doesn't work

### ISSUE THREAD

**Issue by TiagoTiago** [benrugg/AI-Render#16]
### Describe the bug

If I try to render an animation, the output is just the original non-AI render (except if I did do an AI render previously, the first frame gets replaced by the previously AI rendered image even if the scene has actually been modified in the meantime.

ps:If it makes any difference, I believe the Auto1111 script here updates it on every launch, and I fired it up about half an hour or so ago before filing this bug report (so something like about 03:00 UTC on the 22th of October). Lemme know what other details you need.

### To reproduce

Use it normally, but instead of rendering one frame, render in animation mode (Ctrl-F12 by default, or Render Animation in the Render Menu), and then look at the results.

### Error log

There are no error messages, but the addon behaves unexpectedly.

### Environment

- Blender version (upper right corner of splash screen):  3.3.0
- AI Render version (find in Preferences > Add-ons): 0.3.3
- Operating system (Windows/Mac/Linux): Linux

**Comment by benrugg** [comment]
Thanks for submitting this. It's actually listed as a known limitation that animation isn't supported yet. I'm going to close this for now, but I will be adding animation support soon!

**Comment by TiagoTiago** [comment]
Oh, sorry I missed that. Been trying so many different SD stuff lately I forgot I hadn't read the ReadMe for this one yet.

**Comment by benrugg** [comment]
No worries. Yeah, new stuff is coming out almost every day!
