### ISSUE TITLE
loras

### ISSUE THREAD

**Issue by balevato** [benrugg/AI-Render#160]
### Describe the feature you'd like to see:

there is a rich world of creation using loras, maybe its a good idea
also maybe can we use a tools tike animdiff to reinforce consistency
thanks for your addon, its easy to test direct from blender

**Comment by benrugg** [comment]
Yes, this is a good additional feature that I would love to add when I have time. At the moment, I'm keeping AI Render updated, but I don't have the bandwidth to add new features. I'd be happy for anyone else to contribute in this way, though!

closing this in favor of #126
