### ISSUE TITLE
Feature Request: Negative prompt

### ISSUE THREAD

**Issue by f-rank** [benrugg/AI-Render#20]
### Describe the feature you'd like to see:

This is a great addon, I actually completed the 3D guru donut tut while installing it. Great fun to see how it works.
As an SD local user, big part of getting specific results is controlling the negative prompt. Took a look around and couldn't find a way, maybe there is one, if so I missed it.
Tried "--neg" and "Negative prompt:" followed by the negative prompt content but that doesn't seem to be it.

**Comment by benrugg** [comment]
Good call. It doesn't handle this right now, but I will add it to the todo list for the future!

**Comment by Ainaemaet** [comment]
Yes, this one is essential. Negative prompting has become an integral part of my SD workflow and even though I didn't think I would need it here, I quickly hit a wall in what I'm able to create as some scenes/prompts don't play nice and come out with weird things that I just don't want.

**Comment by benrugg** [comment]
Negative prompting is available in the latest release!

Update AI Render in the add-on preferences or get the latest version here: https://github.com/benrugg/AI-Render/releases/tag/v0.6.3

**Comment by benrugg** [comment]
You can add a single negative prompt, or batch test multiple using animated prompts. More info here: https://github.com/benrugg/AI-Render/wiki/Animation#negative-prompts
