### ISSUE TITLE
AI-render for blender installation tutorial

### ISSUE THREAD

**Issue by beelico** [benrugg/AI-Render#21]
### Describe the feature you'd like to see:

Hello

can you give me the address of a video tutorial, from start to finish, on how to install AI-render in blender?

would be the local install of AI-render .

I am not able to install by the available text.

thanks

thanks

**Comment by benrugg** [comment]
Yep: https://www.youtube.com/watch?v=tmyln5bwnO8

**Comment by beelico** [comment]
> Yep: https://www.youtube.com/watch?v=tmyln5bwnO8

I wanted to install AI-render locally in Blender.
the video you indicated is not .

is there another video about the local installation?

thank you so much

**Comment by benrugg** [comment]
Ah, gotcha. For that, I only have these instructions (not a video): https://github.com/benrugg/AI-Render/wiki/Local-Installation

**Comment by benrugg** [comment]
Actually, here's a video I had seen earlier for local installation. Hopefully it's still accurate: https://www.reddit.com/r/StableDiffusion/comments/xle3uw/stable_diffusion_automatic1111_full_installation/
