### ISSUE TITLE
Feature Request: Integrate with Stable Horde

### ISSUE THREAD

**Issue by discodiffuse** [benrugg/AI-Render#22]
### Describe the feature you'd like to see:

ability to use stablehorde api key.

**Comment by benrugg** [comment]
This would be cool. I will look into it at some point.

**Comment by tijszwinkels** [comment]
You read my mind. :)
I'd like to take this one if that's alright.

**Comment by benrugg** [comment]
@tijszwinkels Yes, go for it! Currently, AI Render just does a regular http call to the API's. As long as Stable Horde supports that, it should be pretty straightforward to add another backend.

**Comment by tijszwinkels** [comment]
It's basically done! (https://github.com/tijszwinkels/AI-Render/tree/stable_horde_support)

I'll give it one more good look tomorrow and file a MR.

**Comment by benrugg** [comment]
It's looking great! I appreciate the cleanup around those if statements that can be replaced by `utils.get_active_backend()`. 

Thanks for working on this.

**Comment by tijszwinkels** [comment]
See: https://github.com/benrugg/AI-Render/pull/39

If this is all stable, we could consider having the Stable Horde back-end as default, as that would make the plugin essentially zero-configuration.
However, let's get a few flight-hours on it first. :)

**Comment by benrugg** [comment]
Stable Horde is now available in the latest release! Thank you to @tijszwinkels for making this happen.

Update AI Render in the add-on preferences or get the latest version here: https://github.com/benrugg/AI-Render/releases/tag/v0.6.3
