### ISSUE TITLE
Enable Automatic's 'HiRes Fix' option in AI-Render interface

### ISSUE THREAD

**Issue by Ainaemaet** [benrugg/AI-Render#26]
### Describe the feature you'd like to see:

Hello, if we could hook in and render using the 'HiRes Fix' option included in Automatic1111 that would be amazing. 
I tried enabling it in the UI and running in Blender, but unlike changing models as HiRes Fix is applied after the image is rendered it won't work in the AI-Render plugin the same way. 

I do realize the plugin isn't the Automatic1111-UI and that many of the features of the webui won't translate well to the plugin, but considering how common it is in Blender to render to various aspect ratios I think it would be a great feature to have.

**Comment by benrugg** [comment]
I think maybe the best approach for this is to have a workflow where the rendered image could be send to the UI in Automatic1111, so you can continue to apply changes from there. Like what's described in #18

**Comment by marianobastiUNRN** [comment]
'HiRes Fix' is a process described as such:
`Use a two step process to partially create an image at smaller resolution, upscale, and then improve details in it without changing composition`
It is done to have a more consistent structure on larger resolution generations, as the model was trained with mostly 512x512 images.
I haven't had the need for this function on renders yet, but would be neat to have it available

**Comment by benrugg** [comment]
I will try to dive into this more when I have a chance

**Comment by kryztoval** [comment]
In my personal opinion this does not make sense. HiRes Fix only job is to generate an image in txt2img with a resolution that matches the trained data, then it upscales the image and runs img2img on it.

If I understand correctly this addon is creating a rendered image and then it is running img2img on the rendered image. There is no txt2img generation, and this would mean there is no need for the higres fix.

**Comment by benrugg** [comment]
@kryztoval Thank you for this explanation. You're exactly right that there is no txt2img generation. I will close this.
