### ISSUE TITLE
Feature Request: xno.ai integration

### ISSUE THREAD

**Issue by optionboom** [benrugg/AI-Render#27]
### Describe the feature you'd like to see:

Ability to use xno.ai as the generation source, using their api: xno.ai/api

### Additional information

xno.ai's API is cheaper in bulk than Dreamstudio so it'd be a good alternative, especially for potential future animation support.

**Comment by benrugg** [comment]
This looks really promising! I'd love to be able to integrate with this. Unfortunately at the moment it's only text-to-image, not image-to-image. I'll close this for now, but let me know if they release an image-to-image API.

**Comment by optionboom** [comment]
It looks like the API has been updated to support image-to-image.

**Comment by benrugg** [comment]
@optionboom Thanks for the update. I will check this out as soon as I can. I just released animation support and I'm working on posting demos and instructions right now!
