### ISSUE TITLE
Request: Discord server

### ISSUE THREAD

**Issue by marianobastiUNRN** [benrugg/AI-Render#38]
### Describe the feature you'd like to see:

Having a discord server with the following channels:
  • General
  • faq
  • Ideas and feedback
  • bug report
  • feature request
  • art (and techniques) sharing
  • development general

I've also seen holding voting for new features is a good unofficial way to assess priorities.

I know that most of this can be debated on Github, but on discord chat can be way less structured and the platform is much less intimidating for ones not involved on development, encouraging more engagement.
I can take care of building the server if that's okay.

**Comment by benrugg** [comment]
This is a good idea. It would definitely make coordination easier. If it's ok, I'll watch how busy things get for the next few weeks, and if it ramps up, I'll create a Discord server.
