### ISSUE TITLE
AI render node Muted

### ISSUE THREAD

**Issue by Shadowmunky** [benrugg/AI-Render#4]
### Describe the bug

The AI render node is muted in the beginning. When unmuted , shows black screen.

### To reproduce

Blender default scene> enable AI render> add prompts> Render 

### Expected behavior

Export AI image

### Screenshots/video

![image](https://user-images.githubusercontent.com/86535188/196052077-79a55e55-4071-4721-9e28-5e19874a414a.png)
![image](https://user-images.githubusercontent.com/86535188/196052080-3c418be8-72bf-4057-b084-ca0a6235dc5f.png)

### Environment

- AI Render version: 
- Blender version: 
- Operating system: (Windows, OS X, etc)

**Comment by benrugg** [comment]
@Shadowmunky Thanks for submitting this. Are you seeing any error in the panel (you may have to scroll to it)? Like this screenshot?
<img width="1728" alt="Screen Shot 2022-10-16 at 1 42 17 PM" src="https://user-images.githubusercontent.com/1221274/196052469-832b2a96-204c-41d1-b9a3-e84f73050996.png">

**Comment by ItalicAI24** [comment]
I am also experiencing the same issue. However, I do not see any "error" prompt within the AI Render tab. ![image_2022-10-16_144924025](https://user-images.githubusercontent.com/115946578/196052636-6d7b9317-56e7-49f9-9ecb-a27c3d1ad23d.png)
![image_2022-10-16_144953009](https://user-images.githubusercontent.com/115946578/196052661-1c530500-c708-47a3-8611-aa8dbd1940e1.png)

I can only see black when I attempt to view the AI Render Result node.

**Comment by benrugg** [comment]
@ItalicAI24 Thanks for posting, too. Do you see anything in the panel on the right (see my screenshot above) when you scroll to it?

**Comment by zofoyodee** [comment]
I have the same issue and I don't see an error on the right.  I'm just getting a black screen when I enable the AI Render Node.  I'm using Blender 3.3.

**Comment by benrugg** [comment]
@zofoyodee Just to totally clarify, do you see the AI Render panel on the right, or is it scrolled off the screen?

**Comment by zofoyodee** [comment]
I see the AI panel on the right but I don't see an error.

**Comment by benrugg** [comment]
@zofoyodee ok, thanks for clarifying. Could you open the system console by going to Window > Toggle System Console, then do another render, and send me a screenshot of the console?

**Comment by zofoyodee** [comment]
Is it because my C drive is low on storage?

![screenshot2](https://user-images.githubusercontent.com/115167050/196260818-92f656a8-f787-4fcf-85c6-725ccc98a24a.png)

**Comment by benrugg** [comment]
@zofoyodee oh, super interesting. I think there might just be some obscure bug with the way the filename is getting handled. It looks like the temp file is mixing forward slashes and backslashes. 

I'll address this in a new release as soon as I can. You may be able to fix the issue on your machine by changing or removing the 'temporary files' preference in Blender: 

<img width="662" alt="Screen Shot 2022-10-17 at 2 09 10 PM" src="https://user-images.githubusercontent.com/1221274/196262120-c5c75871-c1cd-4f9c-ac4c-53b67062e4fa.png">

**Comment by zofoyodee** [comment]
That worked!  Thanks :)

![screenshot3](https://user-images.githubusercontent.com/115167050/196269445-0354f24c-f1e3-40bc-9efc-c0224279bd44.png)

**Comment by benrugg** [comment]
@zofoyodee Wonderful! So glad we figured it out. I will try to make sure this doesn't happen to others in the future!

@Shadowmunky @ItalicAI24 This might also be the issue you were experiencing. Feel free to try this fix and let me know (see above).

**Comment by zofoyodee** [comment]
I'm already getting amazing results - this plugin rocks!

**Comment by benrugg** [comment]
@zofoyodee So glad to hear it. I'd love to see some - you can tag me on twitter @ai_render or instagram: @airenderblender

**Comment by ItalicAI24** [comment]
> @zofoyodee Wonderful! So glad we figured it out. I will try to make sure this doesn't happen to others in the future!
> 
> @Shadowmunky @ItalicAI24 This might also be the issue you were experiencing. Feel free to try this fix and let me know (see above).

I'll have to try it and see if it works. My Temporary Files path was already empty so did not notice anything with slashes being weird unless that was referring to the command prompt.

**Comment by benrugg** [comment]
@ItalicAI24 ok, so it might be a different issue, then. If you can post a log, that's what will really help me track it down

**Comment by benrugg** [comment]
I am hoping that the update I'm about to release will fix this issue. For any of you who have a chance tonight, could you try this update and see if it works for you? Remove the existing add-on and install this one (attached).

[AI-Render-v0-2-7.zip](https://github.com/benrugg/AI-Render/files/9815646/AI-Render-v0-2-7.zip)

**Comment by zhoujiujia** [comment]
When I click the "Enable" button,I see a error on the debug channel:
![image](https://user-images.githubusercontent.com/12220545/196594501-849d2df2-bf27-4840-b612-800213e49a20.png)

And then I click again,there's no error.But when I render,I see the black window.
![image](https://user-images.githubusercontent.com/12220545/196594763-a962b37f-1094-47c9-a5cc-c42340c62174.png)

**Comment by sntlks** [comment]
![image](https://user-images.githubusercontent.com/52822395/196619351-4f9eb29e-1836-4559-a4d3-5523046f4680.png)
The AI Render node is grey and invalid

**Comment by shashuer** [comment]
i tried v0-2-7.Same problem. AI Render node is invalid.
![20221019171758](https://user-images.githubusercontent.com/116157115/196650937-e23ee66e-07e9-479a-bfc2-4390af820f7d.png)

**Comment by sntlks** [comment]
![image](https://user-images.githubusercontent.com/52822395/196675781-660db532-cbdd-4c54-8c46-c0232b71d2f7.png)
Fixed~v0-2-7 @benrugg

**Comment by sntlks** [comment]
![image](https://user-images.githubusercontent.com/52822395/196676321-a5104fd1-491d-4bca-8c52-0960987ab00b.png)
It's working~v0-2-7

**Comment by benrugg** [comment]
@sntlks really glad it's working. @zhoujiujia @shashuer your issue is a different that I will fix this morning, too!

**Comment by dingyili1202** [comment]
Amazing! it worked!!! thanks a lot!!!
