### ISSUE TITLE
It continuously give the error of server timing out

### ISSUE THREAD

**Issue by metaverseplus** [benrugg/AI-Render#43]
### Describe the bug

Whenever I click the render button the AI renderer give server times out error

### To reproduce

I do everything correctly but when i click the render bttun it shows the error

### Error log

AI Render Error:  The server timed out. Try again in a moment, or get help. [Get help with timeouts](https://github.com/benrugg/AI-Render/wiki/FAQ#%EF%B8%8F-ai-render-keeps-timing-out)

### Environment

- Blender version (upper right corner of splash screen): 3.3.1
- AI Render version (find in Preferences > Add-ons): 0.5.3
- Operating system (Windows/Mac/Linux): Mac

**Comment by benrugg** [comment]
Every once in a while, the server is overloaded for a minute or two. Can you try again and see if it's working now?

**Comment by benrugg** [comment]
@metaverseplus Checking in on this. Can you try again soon?

**Comment by benrugg** [comment]
@metaverseplus Actually, I've just released a new version which uses a new API on the backend. This should (almost) for sure not timeout 🤞 

Update in the AI Render add-on preferences or get the new version here: https://github.com/benrugg/AI-Render/releases/tag/v0.6.3
