### ISSUE TITLE
Feature Request: Add seed (and possibly other params) to output filename

### ISSUE THREAD

**Issue by ohmygardn** [benrugg/AI-Render#44]
### Describe the feature you'd like to see:

Please add the ability to save the generation seed in the file name.
So I could repeat the result I like. Right now there is a set of digits which looks like a seed, but it has nothing to do with the actual seed. In the related field other digits are displayed.
Also it would be cool if you could add possibility to animate based on previous generation result. So I could generate e.g. 50 shots automatically. 
Right now the animation can only be rendered based on the original image. Thank you!

**Comment by marianobasti** [comment]
Thats a good idea, it would be nice to be able to choose what parameters are annotated in the output filename e.g. sampler, seed, steps, ckpt name.
You will find that in lines 433, 434 and 435 of `operators.py` the names are prepared, that's where these parameters would be appended. Feel free to open a PR with those changes!

**Comment by benrugg** [comment]
Yeah, this is a great idea. I have it on my list for the future. Like @marianobasti suggested, I'd like to actually allow optionally adding the seed, prompt and other params to the filename.

**Comment by benrugg** [comment]
This feature is now available, thanks to @LeonardMeagher2. Update AI Render through the add-on preferences and you can specify a template for the filename.
