### ISSUE TITLE
New install crashes on render.

### ISSUE THREAD

**Issue by drswoboda** [benrugg/AI-Render#45]
### Describe the bug

Fresh install of AI-Render. Simple scene. Simple prompt. Select RENDER in Blender and the plugin ERRORS. Automatic1111 runs fine in my browser window.
-David

[flowers_01.zip](https://github.com/benrugg/AI-Render/files/10079424/flowers_01.zip)
[Blender_SD_RunError.txt](https://github.com/benrugg/AI-Render/files/10079437/Blender_SD_RunError.txt)
[SD_ServerErrorOnRender.txt](https://github.com/benrugg/AI-Render/files/10079438/SD_ServerErrorOnRender.txt)
[SD_ServerLaunch.txt](https://github.com/benrugg/AI-Render/files/10079440/SD_ServerLaunch.txt)

![blender_q8ijKPueRN](https://user-images.githubusercontent.com/7105711/203655698-f13aea68-2d87-48fb-82f9-9d501dc623aa.png)

![blender_MotbfbUW6s](https://user-images.githubusercontent.com/7105711/203655758-0ec34c91-272b-486e-ac38-88bb4c35e1d6.png)

![blender_NantmdhORX](https://user-images.githubusercontent.com/7105711/203655805-356727b5-f752-4e85-89d5-f191b0143abc.png)

### To reproduce

Just try to Render the scene in Blender. Stable Diffusion throws errors in the console.

### Error log

Read prefs: C:\Users\drswo\AppData\Roaming\Blender Foundation\Blender\3.3\config\userpref.blend
Reloading external rigs...
Reloading external metarigs...
_______REgister previews
.. .ao
.. .ao_legacy
.. .bevel_mask
.. .cavity
.. .curvature
.. .diffuse
.. .displacment
.. .dust
.. .id_element
.. .id_material
.. .normal_object
.. .normal_object_bevel
.. .normal_tangent
.. .normal_tangent_bevel
.. .paint_base
.. .position
.. .selection
.. .wireframe
register
Registered MACHIN3tools 1.1.0.DeusEx with 9 tools, 9 pie menus
HardOps 0.9.87.33 available!
Info: Updated sidebar tabs
Read blend: G:\__Projects\__Projects BLENDER\AI Renders\flowers_01.blend
AI Render Error:  An error occurred in the Automatic1111 Stable Diffusion server. Check the server logs for more info.

### Environment

- Blender version (upper right corner of splash screen): 3.1.1
- AI Render version (find in Preferences > Add-ons): 0.5.3
- Operating system (Windows/Mac/Linux): Windows 10 Pro 21H2 b.19044.2251

**Comment by benrugg** [comment]
Yeah, someone else had that issue earlier this week: #42 

It's an error in Automatic1111, and none of us are sure why it's happening. Apparently a fresh install of Automatic1111 will solve it. (You can copy out the large weights file and then copy it back in, so you don't have to download it again, if you want)

**Comment by benrugg** [comment]
PS. Thank you for the diligent work posting all the logs!

**Comment by drswoboda** [comment]
Thanks for the quick reply. I am looking forward to trying your plugin in Blender. It looks really great. I'm glad the bug report was helpful, just trying to make your work a tad bit easier, figuring you can't really give too much information.

**Comment by drswoboda** [comment]
I just did a full reinstall of Automatic1111 Stable Diffusion, and I still get the Render error. I'll put this on the back burner until there is a known solution. Please let me know if you need any more data to help fix this issue. 
Thanks,
-David

**Comment by benrugg** [comment]
ah, lame... That's really weird. I guess you might want to consider posting on Automatic1111 or seeing if there's already an issue about it. It would be the error you saw, while using "img2img in api mode"
