### ISSUE TITLE
" Detail not found " 

### ISSUE THREAD

**Issue by Lluc3DASM** [benrugg/AI-Render#48]
### Describe the feature you'd like to see:

I can't make render AI work with local stable diffusion UI. It works if I use my DreamStudio key, Also stable diffusion UI work from the browser but when I try from blender it does not connect.

serve response {"detail":"Not Found"}

Blender - 3.3.1
Render AI addon - 0.5.3
stable diffusion UI - latest update from 23 ‎November ‎2022

**Comment by marianobasti** [comment]
Do you have any extra arguments when running the server?

**Comment by benrugg** [comment]
My guess would be that it's not running in API mode. Did you follow all the steps here? https://github.com/benrugg/AI-Render/wiki/Local-Installation

**Comment by Lluc3DASM** [comment]
Yes API mode is set "COMMANDLINE_ARGS=--api"

**Comment by benrugg** [comment]
Gotcha. Are there any other logs either from AI Render or Automatic1111?

**Comment by Lluc3DASM** [comment]
On the blender console:
AI Render Error:  An error occurred in the Automatic1111 Stable Diffusion server. Full server response: {"detail": "Not Found"}

On the "stable-diffusion-webui" console
Embeddings:
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

I tried to modify "launch.py" but I cannot see any "share" setting.

**Comment by Lluc3DASM** [comment]
the last one is /startup-events

**Comment by benrugg** [comment]
Yep, that's what I figured. That means it's not running in API mode. (And I was able to replicate it on my end just now with the latest Automatic1111 version. It looks like they changed their response, so I will update AI Render to provide a better error message!)

My guess would be that you are accidentally running `webui.bat` instead of `webui-user.bat`

**Comment by benrugg** [comment]
@Lluc3DASM I'm going to close this, but let me know if you still can't get it working!
