### ISSUE TITLE
Question: Google Analytics

### ISSUE THREAD

**Issue by solosails** [benrugg/AI-Render#58]
Hi there, 

Just noticed after each return from a locally served SD run, the addon is sending something to google analytics? , Can you tell me what's being sent here please? - Thanks!

**Comment by benrugg** [comment]
Yes, I added google analytics last week, so I can watch for errors and have a general sense of usage. It's sending meta/usage info only - never the prompt or image! 

You can see exactly what it's sending here: https://github.com/benrugg/AI-Render/blob/e81ad4976d339ba585c379ac85152ed914d483e1/analytics.py#L126

**Comment by solosails** [comment]
Hi, Thank you for the clarification!
