### ISSUE TITLE
Couldn't create temp directory for images

### ISSUE THREAD

**Issue by coolwant** [benrugg/AI-Render#6]
### Describe the bug

I rendered simple test scene, but blender couldn't render AI Render and showed such a messege "Couldn't create temp dirctory for images"  and didn't funtion rendering (only render base blender render. Didn't rendered AI render)
I relocated other directory for render, but same happen.
* AI Render node is mute too !
*

### To reproduce

Install AI Render
Make simple test scene
Did Render (with AI Render)
Renedered blender Render, but no AI Render
show error log at Prompt :Couldn't create temp dirctory for images

### Expected behavior

Render currectly and save images,

### Environment

- AI Render version: 
- Blender version: 
- Operating system: (Windows, OS X, etc)
-----------------------------
AI Render 0..2.6
Blender 3.1
Window 10

**Comment by benrugg** [comment]
Thanks for posting this. I will do an update that will let you choose a temp directory, which should solve this. So far, this seems like a rare bug, but I will squash it!

**Comment by benrugg** [comment]
@coolwant I think this update should fix the issue. Could you try testing this for me before I release it to everyone else? Remove the existing add-on and install this one (attached). Let me know if it works!
[AI-Render-v0-2-7.zip](https://github.com/benrugg/AI-Render/files/9815638/AI-Render-v0-2-7.zip)

**Comment by coolwant** [comment]
Hi Thank you for quick update !
First time it work! but second when i did render again (Changed parameter...etc), The AI render muted.  same as before bugs list "AI Render nodes muted"

**Comment by benrugg** [comment]
@coolwant Gotcha. Yeah, at the moment, it will likely time out if you do 1024x1024. I plan to add AI upscaling as soon as I can get to it.

**Comment by benrugg** [comment]
Fixed in the latest release. Get it from Blender Market, Gumroad or the [releases page](https://github.com/benrugg/AI-Render/releases/tag/v0.2.8)

Or update in Blender under 'Preferences' > 'Add-ons' > 'AI Render' > 'Updates'

Fixed in a8d18a059e24442f95104e080c71c6ed2d106ae1 and 2db43b2a93a10a3034db9eb6d7e725dfab4db4f3

**Comment by afecelis** [comment]
Hi ben, I'm also getting the error, version 0.10, Windows 10, Blender 3.6.5. Where is the setting or how do you set up the temp folder?

**Comment by benrugg** [comment]
@afecelis - I'm going to open a new issue for this. It has happened to a couple others since the latest version in the past few days, and I need a bit more info to track it down.

**Comment by benrugg** [comment]
@afecelis just in case you didn't get a notification on my new issue, could you see #136
