### ISSUE TITLE
More than 50 steps

### ISSUE THREAD

**Issue by Barbolux** [benrugg/AI-Render#60]
### Describe the feature you'd like to see:

For some cases I would like to take further 100 or 150 steps and the interface limits me to 50.

Thanks for the software, it's working great.  :-)

**Comment by benrugg** [comment]
You know what, 50 is just the "soft limit" for the slider in the ui. You can set it all the way to 150 by just typing in the value.

Just for my own education, I'm curious what use cases actually need that many steps. If you wouldn't mind sharing an example with me, I'd love to see it!
