### ISSUE TITLE
Imac Os Ventura/ Blender/ AI Render / error message

### ISSUE THREAD

**Issue by masje67** [benrugg/AI-Render#62]
### Describe the bug

Hello
I worked with AI render with a plane + JPEG TEXTURE and all was OK 
but oops! Error message  with the same material .
![Sans titre](https://user-images.githubusercontent.com/120774730/208231195-7e4bb44e-627a-422e-aea1-e7b72e20fcc0.png)

thanks for your help and Bravo for your wonderful Addon
![Sans titre](https://user-images.githubusercontent.com/120774730/208231341-94569156-048d-4fd8-97fc-91a0e0b13ea3.png)

ps : I am french and it is difficult for me to explain
cheers

### To reproduce

Imac 2019 / Os ventura / 8 go Ram / Radeon Pro 555X 2 Go / Hd 1 tetra go
open blender
add a plane
add new material = jpeg pic
add image size 960 x 960
add a prompt = music
render and right now error message

But Ii worked with the same pic 2 hours without issues

### Error log

Last login: Sat Dec 17 08:55:02 on ttys000
laurencemas@iMac-de-Jean-MAS-2 ~ % cd /Applications/Blender.app/Contents/MacOS && ./Blender
Read prefs: /Users/laurencemas/Library/Application Support/Blender/3.4/config/userpref.blend

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux):

**Comment by masje67** [comment]
SORRY. I have no credits...I did not understand
So closed for me
thanks
and
excuse me

cheers

**Comment by benrugg** [comment]
Ah, that's helpful to see, actually. I used to have a much clearer error in place for that, but whenever the Stable Diffusion people change their responses, I have to adapt!
