### ISSUE TITLE
Error in Blender 3.5

### ISSUE THREAD

**Issue by Justinandjohnson** [benrugg/AI-Render#63]
### Describe the bug

When i render I get: 

ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. 
![Screenshot 2022-12-22 092801](https://user-images.githubusercontent.com/51091574/209167504-76e10637-478f-43c7-a388-479628a06222.png)
this should not happen!

### To reproduce

Attempt to render using any blender 3.0+

### Error log

ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!
ERROR: Python context internal state bug. this should not happen!

### Environment

- Blender version (3.5): 
- AI Render version (0.6.8): 
- Operating system (Windows 10):

**Comment by Justinandjohnson** [comment]
And yes. I turned off animation render. I even tried an earlier version that came out before the animation feature. No matter what I click, it thinks I'm trying to render an animation. I just want a picture. This was working in the past.

**Comment by benrugg** [comment]
Hmm, very strange. My only guess is that it must be something happening in Blender 3.5. That error message isn't from AI Render - that's something internal to Blender!

I guess the other thing you could try would be disabling other add-ons just to narrow it down...

**Comment by benrugg** [comment]
@Justinandjohnson were you able to track down any other info about this error? Is it still happening?
