### ISSUE TITLE
Ai render mute 

### ISSUE THREAD

**Issue by dingyili1202** [benrugg/AI-Render#64]
### Describe the bug

Hi, I am having the same issue even with the new version of the Ai render. I have been trying the above solutions but none of them worked.

### To reproduce

I entered the prompt, clicked on the rending option, and the image was the same as the model. I checked on the 'compositing node' window and found out the Ai render was muted. I unmuted it but the rending result was still black.

### Error log

![2](https://user-images.githubusercontent.com/121311547/209388204-bee0016f-e2f9-49ad-b005-7b79e290e0ce.png)

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux): 

### Screenshots/video

![1](https://user-images.githubusercontent.com/121311547/209388810-f9db2cf2-443e-4490-86f8-115594a5dbbc.png)
![3](https://user-images.githubusercontent.com/121311547/209388859-a2b7c7db-2f60-4b02-89ad-49e43b99acfa.png)

**Comment by benrugg** [comment]
From that error log, it looks like it's an SSL error happening on your end. See this issue: https://github.com/benrugg/AI-Render/issues/40

And specifically what helped a previous user: https://www.ssl2buy.com/wiki/how-to-fix-err-ssl-protocol-error

I'm going to close this issue, but let me know if you can't get it working!

**Comment by dingyili1202** [comment]
Hi Benrugg/Ai-Render
Thank you for the help. I tried to solve it and it worked out! thank you
and your team for this amazing tool.

**Comment by benrugg** [comment]
Great, really glad you got it working
