### ISSUE TITLE
Switch Stable Horde backend to R2 serving

### ISSUE THREAD

**Issue by db0** [benrugg/AI-Render#66]
### Describe the bug

Stable horde switched recently to defaulting to r2: True. I noticed [in the code](https://github.com/benrugg/AI-Render/blob/e81ad4976d339ba585c379ac85152ed914d483e1/sd_backends/stablehorde_api.py#L134) you don't explicitly specify `r2:false` when sending b64 images, so you need to update the code to either specify `r2:false` or better, adjust your code to allow it to download images from a URL, instead of decoding b64 and use default r2 serving. Using R2 is the suggested approach from the stable horde (and returns images with less compression) as it results in less bandwidth passing through our servers.

### To reproduce

Stable Horde backend is probably broken right now.

### Error log

N/A

**Comment by benrugg** [comment]
Adding @tijszwinkels. Let me know if you don't have time to do this.

**Comment by tijszwinkels** [comment]
Planning on fixing this, this weekend.

**Comment by benrugg** [comment]
@tijszwinkels That's great - thank you
