### ISSUE TITLE
AI Image is black when using Stable Horde

### ISSUE THREAD

**Issue by shanesemler** [benrugg/AI-Render#67]
The scene renders as expected. The image that comes back from the cloud is black. I'm using Stable Horde (cloud). I don't know if this is a problem on my end or the cloud.
AI Render: 0.6.8
Blender: 3.4.1
Windows 10

**Comment by benrugg** [comment]
I think Stable Horde recently changed their API. See #66 - hopefully we'll have this fixed soon!

**Comment by benrugg** [comment]
Fixed in the latest release - update AI Render to get it
