### ISSUE TITLE
Feature Request: Render with alpha/transparency

### ISSUE THREAD

**Issue by coolerinc** [benrugg/AI-Render#70]
### Describe the feature you'd like to see:

There is a transparency for a single image rendering, but when I try to Render Animation it's gone. In Film tab-> Transparent is checked.
Could you add the ability to render animation with alpha?!

**Comment by benrugg** [comment]
This is a good feature request. Stable Diffusion doesn't natively support this, so I haven't tried to implement it on my own. But now that I'm thinking about it more, it could probably be done by using a compositing node setup. I'll keep this open in case anyone wants to try working on this.

**Comment by benrugg** [comment]
After looking into this more, it's definitely not possible with Stable Diffusion at the moment. Closing this for now...
