### ISSUE TITLE
automatic1111/stable diffussion

### ISSUE THREAD

**Issue by prioratron** [benrugg/AI-Render#72]
### Describe the bug

blender 3.4 - 1680 NVIDIA - I am on the WEBUI and is running.

### To reproduce

It looks like the Automatic1111 server is running, but it's not in API mode. [Get help](https://github.com/benrugg/AI-Render/wiki/Local-Installation#troubleshooting)
It looks like the Automatic1111 server is running, but it's not in API mode. [Get help](https://github.com/benrugg/AI-Render/wiki/Local-Installation#troubleshooting)

### Error log

It looks like the Automatic1111 server is running, but it's not in API mode. [Get help](https://github.com/benrugg/AI-Render/wiki/Local-Installation#troubleshooting)
It looks like the Automatic1111 server is running, but it's not in API mode. [Get help](https://github.com/benrugg/AI-Render/wiki/Local-Installation#troubleshooting)

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux):

**Comment by benrugg** [comment]
See the help article steps that specificly address this. You just need to follow the setup steps more carefully to get it running in API mode: https://github.com/benrugg/AI-Render/wiki/Local-Installation#troubleshooting

**Comment by benrugg** [comment]
Based on someone else's comment I just saw, I think automatic1111 changed that file, and I need to update my instructions for a small nuance. You'll need to remove the hash tag symbol at the beginning of the commandline options line, to uncomment it. That should be all that's missing for you, hopefully!
