### ISSUE TITLE
error unable to save image 

### ISSUE THREAD

**Issue by crownut** [benrugg/AI-Render#73]
### Describe the bug

when i render an image with ai render enabled it renders then says unable to save renderd image and i do not get the ai result

### To reproduce

<img width="215" alt="Screenshot 2023-02-18 at 4 25 05 PM" src="https://user-images.githubusercontent.com/125771319/219902011-92aa2ef2-2b07-4833-834e-df35e7027f2f.png">

### Error log

i don't receive an error here

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux):

**Comment by benrugg** [comment]
Sorry, but I can't help if you don't send the logs or other info like your blender version. Instructions are on the bug report page.

**Comment by crownut** [comment]
> Sorry, but I can't help if you don't send the logs or other info like your blender version. Instructions are on the bug report page.

thats fair but there is no error in the console, i'm running blender on mac, and the version is 3.0

**Comment by crownut** [comment]
> Sorry, but I can't help if you don't send the logs or other info like your blender version. Instructions are on the bug report page.

my appologies i misread i thought it wanted the blender consul let me check the mac console my appologies

**Comment by benrugg** [comment]
Ah, gotcha. Yeah, now that I think about it, that tracks. I think AI Render is detecting that error and handling it. Unfortunately, I haven't see this actually happen any other time, and I have no idea how to make it work 😥

My guess would be that something about your Blender installation directories are marked without "write" permission, so it's failing when trying to save to disk. But I'm not sure how to fix that. 

Even more unfortunately, I'm traveling without my computer right now, so I can't even look into it more. I love you my only thought is that you could Google something like "blender can't save to disk" and see if there any suggestions. 

What blender version and OS are you using?

**Comment by benrugg** [comment]
Also, apologies in advance if I can't respond until tomorrow. I'm boarding a plane right now!

**Comment by crownut** [comment]
> Also, apologies in advance if I can't respond until tomorrow. I'm boarding a plane right now!
Read prefs: /Users/shanehohler/Library/Application Support/Blender/3.1/config/userpref.blend
The custom presets directory seems invalid: /Remap Presets/
reloading addon: AI-Render 1676760001.9143229 1676760228.5369709 '/Users/shanehohler/Library/Application Support/Blender/3.1/scripts/addons/AI-Render/__init__.py'
Modules Installed () from '/Users/shanehohler/Downloads/AI-Render.zip' into '/Users/shanehohler/Library/Application Support/Blender/3.1/scripts/addons'
WARN (bpy.rna): source/blender/python/intern/bpy_rna.c:1352 pyrna_enum_to_py: current value '120' matches no enum in 'AIRProperties', '', 'sampler'
AI Render Error: Couldn't save rendered image

**Comment by benrugg** [comment]
My new guess based on that log is that it has something to do with the "custom presets directory". If you know what that is, try disabling that. If you didn't set that up on purpose, try googling around that. Something about your Blender installation isn't standard.
