### ISSUE TITLE
api flag not recognised in blender 

### ISSUE THREAD

**Issue by 1nky** [benrugg/AI-Render#74]
### Describe the bug

Hi .... I'm not able to get the addon to work in blender ... It works fine on it's own as a local installation, how ever when i render in blender i get the error "It looks like Automatic1111 server is running but is not in api mode" .
I have edited both the webui-user.sh file and have tried it after also editing the webui.bat file with the same results... i have also tried using the binary download of blender as i had originally built it from source...  

### To reproduce

I see the local sever running webui but when i hit render i just get a cycles render and not the prompted render...
followed by the error.  

### Error log

The above command does not work in Linux (or mint any way)... I tried to use --debug-ghost (just got thre same api error), and --addons <addon(s)> but not sure of the syntax and which file is exactly the ai render addon.  I spelt it as i saw it in the command line error

ie 
  --addons ,AI Render ... but it did not find the files and gave an error 
would be happy to run it if you could give me the command that would give the output that you would like to see

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux): 

Blender-3.4.1-linux-x64

AI Render --0.6.9

Release Linux Mint 21.1 Vera 64-bit
Kernel Linux 5.15.0-60-generic x86_64
MATE 1.26.0

### Screenshots/video

![Screenshot at 2023-02-18 21-35-42](https://user-images.githubusercontent.com/35410735/219900714-ae660843-863e-46e9-baab-1c6785827a04.png)
![Screenshot at 2023-02-18 21-38-13](https://user-images.githubusercontent.com/35410735/219900722-fca94cc8-dc1e-4c9d-b71c-b6666071778f.png)
![Screenshot at 2023-02-18 22-21-15](https://user-images.githubusercontent.com/35410735/219902004-4174e5c2-d88b-4f9f-aaaf-4b8a0a21f4f0.png)

### Additional information

I'm on GMT time so i may be offline when you're on, but i will get back at some point... 
Great addon by the 
Thanks

**Comment by benrugg** [comment]
thanks for posting all the screenshots. That's super helpful. The line in webui-user.sh with the "--api" flag just needs to be uncommented. (delete the hash tag symbol at the beginning of that line).

I just realized that automatic1111 changed that file and I need to update my instructions!

**Comment by 1nky** [comment]
Thanks Ben! 
feel like a right dufus for not un commenting the argument...
