### ISSUE TITLE
AI: Stability for Blender installed and it does not appear in the list of tools

### ISSUE THREAD

**Issue by eyesdrib** [benrugg/AI-Render#76]
### Describe the bug

Using the method described by Pixxo 3D on Youtube, https://youtu.be/Y-H2Rp24HOY, installed Stability in Prefs, enabled it, got an API link and pasted it in the add-on. It does not appear in Render Properties in Blender. I am running Blender 3.4.1.

### To reproduce

1) Download AI: Stability for Blender
2) Start Blender
3) Go to Edit/Preferences
4) "Install" from download on PC (Windows 10)
5) Enable Stability
6) Get an API key from Dreamstudio
7) Restart Blender

### Error log

Read prefs: C:\Users\henry\AppData\Roaming\Blender Foundation\Blender\3.4\config\userpref.blend
dreamstudio addon: Verbose is enabled
dreamstudio addon: Read in JSON settings from file
register_class(...):
Warning: 'panel.stability_image_editor' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'panel.stability_3D' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'RenderOptionsPanelSection3DEditor' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'RenderOptionsPanelSectionImageEditor' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'AdvancedOptionsPanelSection3DEditor' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'AdvancedOptionsPanelSectionImageEditor' does not contain '_PT_' with prefix and suffix
init
init

### Environment

- Blender version (upper right corner of splash screen): 3.4.1
- AI Render version (find in Preferences > Add-ons): Cycles Render Engine
- Operating system (Windows/Mac/Linux): Windows 10

### Screenshots/video

Render Properties Tab:
![image](https://user-images.githubusercontent.com/10911526/223187339-0991df49-d726-412a-bf13-249b2a838bae.png)

Preferences-Add-ons:
![image](https://user-images.githubusercontent.com/10911526/223187608-6bf95db4-f63e-4ca0-aff8-65ac331b0329.png)

### Additional information

Know that I appreciate your help.

**Comment by benrugg** [comment]
In case someone else ends up here, the answer to this is that this isn't AI Render. Instead, the other Stable Diffusion add-on for Blender has been installed: https://blendermarket.com/products/stability-for-blender

See their page for where to find their add-on in Blender (in the 3D viewport).
