### ISSUE TITLE
Feature request: API key (auth) support for selfhosted remote server

### ISSUE THREAD

**Issue by foxytocin** [benrugg/AI-Render#78]
- API key support for Automatic1111 (local) and **remote selfhosted servers**
- API key support for Dream Studio (cloud) and Stable Horde (cloud) is limited to fixed nonchangeable IP-Adresses.

**Comment by benrugg** [comment]
Not sure exactly what you're asking... You would like UI for changing the url of the backends?

**Comment by foxytocin** [comment]
Kind of: Dream Studio (cloud) and Stable Horde (cloud) could be used with API key but those URLs are fixed and Automatic1111 (local) doesn't support an API key.

I wan't to use my own local or remote server with and API key. Therefore beside the 'Local Web Server URL' field, additional fields for 'user' and 'pass' are needed. There the plugin has to submit request with an authentication header:

1. Encode user:pass into base64 encoding.
2. Add Authorization: Basic <base64> to every request headers while <base64> is the base64-encoded string from 2).

Source: https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/4733

**Comment by benrugg** [comment]
Ah, gotcha. This is outside the scope of something I plan to do with AI Render. You can fork it and edit `sd_backends/automatic1111_api.py` to make this work for you, though.
