### ISSUE TITLE
Feature request: Show UI for changing image size once it's been set

### ISSUE THREAD

**Issue by XeonG** [benrugg/AI-Render#80]
that is all.. seems like a small thing, but found that pretty annoying to get around if wanting to change SD image resolution.

**Comment by benrugg** [comment]
Yes, this is a good call, and few others have mentioned it. It's on my todo list to improve the ui for this. Right now if you change the image size the standard blender way (through render settings), then the AI Render panel for image size will appear again. But that's not very intuitive!

**Comment by benrugg** [comment]
This is now done: https://github.com/benrugg/AI-Render/releases/tag/v0.7.5

(or update through AI Render add-on preferences)
