### ISSUE TITLE
Hello,I use the offline version of stable diffusion，I want to ask, can I use Lora or a model (ckpt、VAE)? How do I set it up?

### ISSUE THREAD

**Issue by nealxu2** [benrugg/AI-Render#83]
### Describe the feature you'd like to see:

Hello,I use the offline version of stable diffusion，I want to ask, can I use Lora or a model (ckpt、VAE)? How do I set it up?

### Additional information

![image](https://user-images.githubusercontent.com/128347195/228310458-55c7c163-a37f-4640-b91d-99b094674b29.png)
![image](https://user-images.githubusercontent.com/128347195/228310592-784f8c28-6bee-402a-812b-04f81b130ab0.png)

**Comment by benrugg** [comment]
Yes, you can choose the model through the Automatic1111 UI first, and then it will be used by AI Render. The presets (the thumbnail images in your screenshot - Anime, Abstract, Iridescent, etc) are a different thing. Those are just extra words added to your prompt.

**Comment by nealxu2** [comment]
I see. Thank you for your guidance
