### ISSUE TITLE
ControlNet is not available?

### ISSUE THREAD

**Issue by nealxu2** [benrugg/AI-Render#84]
### Describe the bug

ControlNet is not available?

### To reproduce

Invalid startup

### Error log

![image](https://user-images.githubusercontent.com/128347195/228313142-c764dc5e-a113-4cbc-b8f1-96af285de687.png)

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux): windows

### Screenshots/video

![image](https://user-images.githubusercontent.com/128347195/228313007-c94606ea-aacb-4882-9f39-40d5cddffee2.png)
![image](https://user-images.githubusercontent.com/128347195/228313049-dc9842bf-3cd7-4d13-b94e-799a7e7884b3.png)

**Comment by nealxu2** [comment]
![image](https://user-images.githubusercontent.com/128347195/228317217-de58ed17-d513-4912-b23a-a42098a5cf81.png)
![image](https://user-images.githubusercontent.com/128347195/228317273-cb927fba-2783-4c8c-89a8-e20acce2ca8c.png)

Could it not be loaded because of a file path problem?

**Comment by nealxu2** [comment]
It has already been resolved. You can use the latest version of ControlNet

**Comment by benrugg** [comment]
Sorry I didn't have a chance to get to this yesterday. I'm glad you got it working.
