### ISSUE TITLE
Local Installation option is not appearing

### ISSUE THREAD

**Issue by Haligator1** [benrugg/AI-Render#86]
### Describe the bug

In the Blender Preferences window, in the AI:  Stability for Blender settings, there is no text below the “Auto-check for updates” check box.  The plugin is up to date.  Automatic1111 is up to date (git pull).

The issue appeared after the git pull for Automatic1111.  I am running Ubuntu 20.04.

### To reproduce

1.  Renders were developing progressively worse blue patches in Blender.  Renders were fine in Automatic1111.  Uninstalled plugin and reinstalled.  No option to use local installation.
2.  Open a Terminal in the Automatic1111 folder.
3.  git pull
4.  The line in webui-use.sh was already changed. to  export COMMANDLINE_ARGS="--api" from previous installation.
5. Close all apps.  Restart laptop. Open Automatic1111, then Blender, then Blender Preferences.  Still no option to use local installation.  Renders are still fine in Automatic1111.

I believe this may be due to the “git pull”, which did successfully update Automatic1111.

### Error log

These directions don’t work for Linux.  “ cd /Applications/Blender.app/Contents/MacOS && ./Blender” is specifically MacOS.

### Environment

- Blender version (upper right corner of splash screen):   3.4.1
- AI Render version (find in Preferences > Add-ons):   0.0.16
- Operating system (Windows/Mac/Linux):   Ubuntu 20.04

**Comment by benrugg** [comment]
So the add-on "AI: Stability for Blender" is not my add-on 😉

If you want to use Automatic1111, you'll need AI Render. You can get it on the GitHub releases page in this same repo, or you can get it here: https://blendermarket.com/products/ai-render
