### ISSUE TITLE
Stable Diffusion Add-on for Blender

### ISSUE THREAD

**Issue by Maria252560** [benrugg/AI-Render#87]
### Describe the bug

The render doen't work. 
This message appears: "(Server Error) An error occurred in the Stability API. Full server response: Your organization does not have enough balance to request this action (need $0.002000527000000003, have $0.00173675 in active grants, $0 in balance)."
I couldn't understand. Please, how to fix this?

### To reproduce

I followed all the steps in the indicated video.
PC: windows

### Error log

Read prefs: C:\Users\zuzam\AppData\Roaming\Blender Foundation\Blender\3.5\config\userpref.blend
Info: Deleted 1 object(s)

Read blend: D:\Spatial Myah\AI\teste3.blend

### Environment

- Blender version (upper right corner of splash screen): 
- AI Render version (find in Preferences > Add-ons): 
- Operating system (Windows/Mac/Linux): 

### Screenshots/video

https://drive.google.com/drive/folders/1QZINAONvQ-YrfAkjktRpJKuWR4ug9zuC?usp=share_link

**Comment by benrugg** [comment]
This means that you have run out of credits on Dresmstudio. You'll need to purchase some, or switch to a different backend. you can run it for free on Stable Horder or on your own computer. Set it to Stable Horde in the add-on preferences or see instructions for local installation here: /wiki/local-installation

**Comment by benrugg** [comment]
Better link: https://github.com/benrugg/AI-Render/wiki/Local-Installation

**Comment by Maria252560** [comment]
Thank you. I got it set up, but now the following message appears: "Error: The local Stable Diffusion server couldn't be found. It's either not running, or it's running at a different location than what you specified in the add-on preferences." Please, help me.

**Comment by benrugg** [comment]
Unfortunately, Automatic1111 can be really tough to fully install. I can't help more than what I've already written in the Troubleshooting section on that page. Make sure you can access the Automatic1111 server through the website http://127.0.0.1:7860/ and if that's not working, you'll need to look to their community for help.
