### ISSUE TITLE
Questions about ControlNet and Checkpoints and Lora etc...

### ISSUE THREAD

**Issue by MaxWHIPshoes** [benrugg/AI-Render#91]
### Describe the feature you'd like to see:

Hello, I'm using Stable Diffusion with Automatic1111. I just downloaded your addon and it seems to be a great tool. I'm just looking for all the extensions I got on Stable Diffusion. I want to select my own Checkpoint (.ckpt files), I'd like to use ControlNet maybe?
Is it something already available? Or maybe in a near future?

Thank You in advance

>

**Comment by benrugg** [comment]
Great question. There's sort of a nuanced answer:
 - you can use your own models (.ckpt files) by choosing them in the web ui and then rendering with AI Render
 - I'm just about to release a version with ControlNet support! (you can grab the beta here, and I'll release an even more updated version very soon: https://github.com/benrugg/AI-Render/wiki/ControlNet)
 - The new version I also has support for upscaling
 - there's not currently a way to use any of the other scripts/extensions
