### ISSUE TITLE
Allow ControlNet weight parameter to be adjusted

### ISSUE THREAD

**Issue by steve-salmond** [benrugg/AI-Render#94]
### Describe the feature you'd like to see:

Just a small convenience - allow users to adjust the amount of influence ControlNet has on rendered output.  Here's the equivalent section in Auto 1111:

![image](https://user-images.githubusercontent.com/1191379/232161566-7ad60892-b8c8-4131-893a-1f993e049ac7.png)

I'll submit a pull request - hopefully! :)

**Comment by benrugg** [comment]
I forgot to close this when it was done several months ago!
