### ISSUE TITLE
RFC: SHARK backend for AI-Render

### ISSUE THREAD

**Issue by powderluv** [benrugg/AI-Render#96]
### Describe the feature you'd like to see:

[SHARK](https://github.com/nod-ai/SHARK) provides a new way of using compilers to generate fast and retarget -able machine learning code. 

We provide a REST API that is backwards compatible with auto1111 that can run AI-Render (Setup instructions are here https://github.com/nod-ai/SHARK/blob/main/docs/shark_sd_blender.md ) but we are enabling our API to include a lot more features like in/out painting, controlnet, upscaling etc.  

We demonstrated using AI-Render [here](https://nod.ai/ultra-realistic-generative-ai-based-rendering-in-blender-with-shark-and-amd-radeon-pro-w7900-gpus/)

We would like to integrate a new SHARK backend and then start enabling the new features. We would like to know if this is something that is of interest before we try to send PRs.

(And thank you for this project).

**Comment by benrugg** [comment]
This looks like a cool project. I'd be honored for you / your team to integrate it with AI Render. 

Just so I understand what SHARK does, is the core value proposition the speed that it offers? Or is there a plan later to also allow for easier installation of projects like Automatic1111?

I'd be happy to review PR's, and I can try to be pretty responsive (time-wise). I should probably say right up front that this is a side project, so I won't always have time to review/merge/release everything immediately.

**Comment by powderluv** [comment]
yeah the value prop is speed and retarget-ability so you should be able to use it across AMD, Nvidia, Intel and macOS GPUs (which we support currently at various levels).  It is an easy install -- just download one .exe and double click :)

No worries at all. We can maintain a fork and push changes upstream as they get accepted.

**Comment by benrugg** [comment]
Sounds great. I'll watch for PR's. Let me know if you have any questions as you go through the code!

**Comment by benrugg** [comment]
Added in https://github.com/benrugg/AI-Render/pull/114
