### ISSUE TITLE
Upscaler only outputs "cutout" images with transparency

### ISSUE THREAD

**Issue by HyperStudio-2020** [benrugg/AI-Render#97]
### Describe the bug

The upscale function cuts away bug chunks of the image and makes it transparent 

### To reproduce

- render default scene with default settings
- Enable AI render, enable upscaling (model does not matter)

### Error log

....................

### Environment

- Blender version (3.4): 
- AI Render version (find in Preferences > Add-ons):  0.7.6 - 0.7.8
- Operating system (Windows/Mac/Linux): Windows 11

### Screenshots/video

<img width="1605" alt="Screenshot 2023-04-20 231539" src="https://user-images.githubusercontent.com/43063146/233489555-21d96f58-ac40-4d6a-8924-7ad319c76b8e.png">

**Comment by benrugg** [comment]
Wow, that's very strange... I have no idea what is happening there. Would you be able to upload the `.blend` file so I can see if I can reproduce it?
